/** Textos fijos de la planilla Resumen Final (31059/31060). */
export const RF = {
  III_ESTUDIANTE: "III: Identificación del Estudiante",
  IV_RENDIMIENTO: "IV: Resumen Final del Rendimiento",
  NRO: "N°",
  CEDULA_IDENTIDAD: "Cédula de\nidentidad",
  LUGAR_NACIMIENTO: "Lugar de\nnacimiento",
  FECHA_NACIMIENTO: "Fecha de\nnacimiento",
  ANO: "AÑO",
  AREAS_FORMACION: "ÁREAS DE FORMACIÓN",
  PARTICIPACION_GRUPOS:
    "PARTICIPACIÓN EN GRUPOS DE\nCREACIÓN, RECREACIÓN Y\nPRODUCCIÓN",
  COMPONENTE_GENERAL: "COMPONENTE GENERAL",
  COMPONENTE_PRODUCTIVO: "COMPONENTE PRODUCTIVO",
  GRUPO: "GRUPO",
  GP: "GP",
  ANO_ESCOLAR: "I. AÑO Escolar:",
  TIPO_EVALUACION: "Tipo de Evaluación:",
  MES_Y_ANO: "     Mes y AÑO:",
  TITULO: "RESUMEN FINAL DEL RENDIMIENTO ESTUDIANTIL",
  codigoFormato: (tipo: string) => `Código del Formato: EMG ${tipo}`,
  II_INSTITUCION: "II. Datos de la Institución Educativa:",
  CODIGO_INSTITUCION: "Código de la Institución Educativa:",
  EPONIMO: "Epónimo:",
  DIRECCION: "Dirección:",
  TELEFONO: "Teléfono:",
  CEDULA_IDENTIDAD_LABEL: "Cédula de identidad:",
  OBSERVACIONES: "VII. Observaciones:",
} as const;
