project_id = "hqiqvegpyxsshxkdyigs"

[functions.send-email]
verify_jwt = false

[functions.get-user-emails]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false

[functions.create-system-admin]
verify_jwt = false

[functions.create-family]
verify_jwt = false

[functions.create-teacher]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.impersonate-user]
verify_jwt = false

[functions.suspend-user]
verify_jwt = false

[functions.update-system-admin]
verify_jwt = false

[functions.update-family-password]
verify_jwt = false

[functions.update-teacher-password]
verify_jwt = false

[functions.resend-welcome-email]
verify_jwt = false

[functions.record-attendance]
verify_jwt = false

[functions.fetch-bcv-rates]
verify_jwt = false

[functions.manage-school-subuser]
verify_jwt = false

[functions.image-proxy]
verify_jwt = false

[functions.send-test-email]
verify_jwt = false

[functions.import-school-data]
verify_jwt = false
