-- Ya no se monta en Docker: supabase/postgres aplica sus propios init-scripts y migrate.sh.
-- Montar un 00-init.sql que crea roles (anon, etc.) choca con la migración oficial:
-- ERROR: role "anon" already exists
--
-- Contraseñas para PostgREST / GoTrue / Storage: ver zz-set-role-passwords.sh en docker-compose.
